language: python
sudo: false
env:
    matrix:
        - TOX_ENV=py34
        - TOX_ENV=py27
install:
    - pip install --upgrade pip
    - pip install tox coveralls
script:
    - tox -e $TOX_ENV
after_success:
    - coveralls

